# server配置
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      timeout: 864000
      # session 过期时间



# mybatis-plus的配置
mybatis-plus:
  type-aliases-package: com.esdllm.usercenter.model
  global-config:
    db-config:
      logic-delete-field: isDelete  #全局逻辑删除
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
      table-prefix:  # 设置表的前缀
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
spring:
  profiles:
    # 加载的配置文件
    include:
      - dev
    # 激活的配置文件
    active: dev
