# 连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///esdllm
    username: root
    password: aa152773652
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    generator:
      write-numbers-as-strings: true