# 连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://rm-wz9g81gr0r33m2h59oo.mysql.rds.aliyuncs.com/esdllm
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    generator:
      write-numbers-as-strings: true